name: CI/CD

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v5
            - name: PHPUnit Tests
              uses: php-actions/phpunit@v2
              with:
                  bootstrap: vendor/autoload.php
                  configuration: tests/phpunit.xml

    tag:
        needs: [tests]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: New version tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v5.5
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            changelog: ${{ steps.tag_version.outputs.changelog }}

    release:
        runs-on: ubuntu-latest
        needs: [tag]
        steps:
            - uses: actions/checkout@v2
            - name: Create Release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ needs.tag.outputs.tag }}
                  release_name: ${{ needs.tag.outputs.tag }}
                  body: ${{ needs.tag.outputs.changelog }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
